# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'duythanh.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


import cv2
import numpy as np
from PyQt5.QtGui import QPixmap
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import *
from detect import run
from PIL import Image


class Ui_MainWindow(QWidget):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(803, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(0, 469, 801, 91))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.groupBox = QtWidgets.QGroupBox(self.horizontalLayoutWidget_2)
        self.groupBox.setObjectName("groupBox")
        self.pushButton = QtWidgets.QPushButton(self.groupBox)
        self.pushButton.setGeometry(QtCore.QRect(140, 30, 111, 41))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_2.setGeometry(QtCore.QRect(560, 20, 111, 41))
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_2.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(0, 0, 381, 461))
        self.groupBox_2.setObjectName("groupBox_2")
        self.input_hinhanh = QtWidgets.QLabel(self.groupBox_2)
        self.input_hinhanh.setGeometry(QtCore.QRect(10, 20, 371, 441))
        self.input_hinhanh.setText("")
        self.input_hinhanh.setObjectName("input_hinhanh")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(389, -1, 411, 461))
        self.groupBox_3.setObjectName("groupBox_3")
        self.output_hinhanh = QtWidgets.QLabel(self.groupBox_3)
        self.output_hinhanh.setGeometry(QtCore.QRect(0, 20, 411, 251))
        self.output_hinhanh.setText("")
        self.output_hinhanh.setObjectName("output_hinhanh")
        self.putput_predict = QtWidgets.QLabel(self.groupBox_3)
        self.putput_predict.setGeometry(QtCore.QRect(0, 270, 221, 191))
        self.putput_predict.setText("")
        self.putput_predict.setObjectName("putput_predict")
        self.textBrowser = QtWidgets.QTextBrowser(self.groupBox_3)
        self.textBrowser.setGeometry(QtCore.QRect(220, 270, 191, 191))
        self.textBrowser.setObjectName("textBrowser")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 803, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.pushButton.clicked.connect(self.browse)
        self.pushButton_2.clicked.connect(self.detection)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "Chức năng"))
        self.pushButton.setText(_translate("MainWindow", "Chọn file"))
        self.pushButton_2.setText(_translate("MainWindow", "Run"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Hình ảnh"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Kết quả"))
    def browse(self, MainWindow):
        self.image_path, _ = QFileDialog.getOpenFileName(
            self, 'Mở  File', '.')
        img = QPixmap(self.image_path)
        img = img.scaled(371, 441)
        self.input_hinhanh.setPixmap(img)

    def detection(self, MainWindow):
        img,text = run(weights='best.pt', source=self.image_path, view_img=False, save_crop=True, nosave=True, line_thickness=3)
        cv2.imwrite("filename.jpg", img)
        img = QPixmap('filename.jpg')
        img = img.scaled(221, 191)
        self.putput_predict.setPixmap(img)

        img2, text2 = run(weights='bestfinal.pt', source='crop_image.jpg', view_img=False, save_crop=True, nosave=True, line_thickness=3)
        cv2.imwrite("filenamenew.jpg", img2)
        img2 = QPixmap('filenamenew.jpg')
        height, width, _ = cv2.imread('filenamenew.jpg').shape
    
        if width >= 411 or height >= 251:
            img2 = img2.scaled(411, 251)
        self.output_hinhanh.setPixmap(img2)
        # self.textBrowser.setPlaceholderText(text2)
        a = " " 
        if ( height/width < 0.4  ):
            for i in text2:
                a = a + i[2]       
        else:
            tempnew2 = sorted(text2,key= lambda x :x[1])
            tempnew3 = sorted([tempnew2[0],tempnew2[1],tempnew2[2],tempnew2[3]],key= lambda x :x[0])       
            for i in tempnew3:
                a = a + i[2]
            tempnew4 = []
            for i in range(4, len(tempnew2)):
                tempnew4.append(tempnew2[i])
            tempnew4 = sorted(tempnew4,key= lambda x :x[0])
            for i in tempnew4:
                a = a + i[2]
        print( "cao dai", height, width)    

        self.textBrowser.setHtml('<h1 style=" text-align: center; height: 191px; ">'+ a + '</h1>')

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
