# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import cv2
from PyQt5.QtGui import QPixmap
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import *
from detect import *
import detect


class Ui_MainWindow(QWidget):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setFixedSize(1029, 572)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setObjectName("widget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.groupBox_2 = QtWidgets.QGroupBox(self.widget)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.input_hinhanh = QtWidgets.QLabel(self.groupBox_2)
        self.input_hinhanh.setText("")
        self.input_hinhanh.setObjectName("input_hinhanh")
        self.verticalLayout_2.addWidget(self.input_hinhanh)
        self.horizontalLayout_3.addWidget(self.groupBox_2)
        self.groupBox_3 = QtWidgets.QGroupBox(self.widget)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.output_hinhanh = QtWidgets.QLabel(self.groupBox_3)
        self.output_hinhanh.setText("")
        self.output_hinhanh.setObjectName("output_hinhanh")
        self.verticalLayout_3.addWidget(self.output_hinhanh)
        self.horizontalLayout_3.addWidget(self.groupBox_3)
        self.verticalLayout.addWidget(self.widget)
        self.widget_2 = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.widget_2.sizePolicy().hasHeightForWidth())
        self.widget_2.setSizePolicy(sizePolicy)
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.groupBox = QtWidgets.QGroupBox(self.widget_2)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton = QtWidgets.QPushButton(self.groupBox)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_2.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_2.addWidget(self.pushButton_2)
        self.horizontalLayout.addWidget(self.groupBox)
        self.verticalLayout.addWidget(self.widget_2)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.pushButton.clicked.connect(self.browse)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Hình ảnh"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Kết quả"))
        self.groupBox.setTitle(_translate("MainWindow", "Tính năng"))
        self.pushButton.setText(_translate("MainWindow", "Chọn file"))
        self.pushButton_2.setText(_translate("MainWindow", "RUN"))

    # def show_img(self, MainWindow):
    #     self.input_hinhanh.setPixmap(QPixmap("input.png"))
    #     self.output_hinhanh.setPixmap(QPixmap("output.jpg"))

    def browse(self, MainWindow):
        filename, _ = QFileDialog.getOpenFileName(self, 'Open File', '.')
        height, width , _ = cv2.imread(filename).shape
        img  = QPixmap(filename)
        img = img.scaled(500,500)
        self.input_hinhanh.setPixmap(img)
    
    def detection(self, MainWindow):
        opt = "Namespace(agnostic_nms=False, augment=False, classes=None, conf_thres=0.25, data=WindowsPath('data/coco128.yaml'), device='', dnn=False, exist_ok=False, half=False, hide_conf=False, hide_labels=False, imgsz=[640, 640], iou_thres=0.45, line_thickness=3, max_det=1000, name='exp', nosave=True, project=WindowsPath('runs/detect'), save_conf=False, save_crop=False, save_txt=False, source='image4.jpg', update=False, view_img=True, visualize=False, weights=WindowsPath('best.pt'))"
        detect.main(opt)



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.detection()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
    
